services:
  bot:
    env_file:
      - .env.production
    restart: unless-stopped
    build:
      context: .
    environment:
      APP_ID: ${APP_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PUBLIC_KEY: ${PUBLIC_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - 3000:3000

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
