name: Build and Push Docker Image
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/scRoll

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug Tags
        run: echo "${{ steps.meta.outputs.tags }}"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
          
      - name: Update Docker image on Server
        uses: appleboy/ssh-action@v1.2.0
        env:
          APP_ID: ${{ secrets.SCROLL_PROD_APP_ID }}
          DISCORD_TOKEN: ${{ secrets.SCROLL_PROD_DISCORD_TOKEN }}
          PUBLIC_KEY: ${{ secrets.SCROLL_PROD_PUBLIC_KEY }}
          SESSION_SECRET: ${{ secrets.SCROLL_PROD_SESSION_SECRET }}
        with:
          host: ${{ secrets.SERVERHOST }}
          username: ${{ secrets.SERVERUSER }}
          password: ${{ secrets.SERVERPASS }}
          port: ${{ secrets.SERVERPORT }}
          script_path: ./deployment/runScrollOnServer.sh
